export default [
    { values: { color: '#305893', backgroundColor: '#f8f8f8', patternColor: '#ccccfc' }, label: 'Sailor', theme: 'bright' },
    { values: { color: '#f25b3d', backgroundColor: '#ffecd5', patternColor: '#ffffff' }, label: 'Honeycomb', theme: 'bright' },
    { values: { color: '#ff3c63', backgroundColor: '#ffc3e2', patternColor: '#ffffff' }, label: 'Candy', theme: 'bright' },
    { values: { color: '#ff3c63', backgroundColor: '#fffac2', patternColor: '#ffffff' }, label: 'Summer', theme: 'bright' },
    { values: { color: '#212121', backgroundColor: '#ffffff', patternColor: '#c7c7c7' }, label: 'Typewriter', theme: 'bright' },
    { values: { color: '#028090', backgroundColor: '#feffe1', patternColor: '#d2ffb3' }, label: 'Lemon', theme: 'bright' },
    { values: { color: '#e63946', backgroundColor: '#a8dadc', patternColor: '#f1faee' }, label: 'Buttons', theme: 'bright' },
    { values: { color: '#432987', backgroundColor: '#ffffff', patternColor: '#c8bfd1' }, label: 'Lavender', theme: 'bright' },
    { values: { color: '#363d6b', backgroundColor: '#ceeff0', patternColor: '#c4dfec' }, label: 'Jeans', theme: 'bright' },
    { values: { color: '#364958', backgroundColor: '#e5fbf4', patternColor: '#aed4bc' }, label: 'Leaf', theme: 'bright' },
    { values: { color: '#df3a55', backgroundColor: '#f3c3bd', patternColor: '#ffefe7' }, label: 'Strawberry', theme: 'bright' },
    { values: { color: '#1e383e', backgroundColor: '#ffffff', patternColor: '#9bfff3' }, label: 'Diamond', theme: 'bright' },
    { values: { color: '#', backgroundColor: '', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
]