export default [
    { values: { color: '#305893', backgroundColor: '#f8f8f8', patternColor: '#ccccfc' }, label: 'Sailor', theme: 'bright' },
    { values: { color: '#ff6600', backgroundColor: '#ffecd5', patternColor: '#ffbc90' }, label: 'Orange', theme: 'bright' },
    { values: { color: '#ff3c63', backgroundColor: '#ffc3e2', patternColor: '#ffffff' }, label: 'Candy', theme: 'bright' },
    { values: { color: '#ff3c63', backgroundColor: '#fffac2', patternColor: '#ffffff' }, label: 'Summer', theme: 'bright' },
    { values: { color: '#212121', backgroundColor: '#ffffff', patternColor: '#c7c7c7' }, label: 'Typewriter', theme: 'bright' },
    { values: { color: '#028090', backgroundColor: '#f0f3bd', patternColor: '#b5feb2' }, label: 'Citrus', theme: 'bright' },
    { values: { color: '#e63946', backgroundColor: '#a8dadc', patternColor: '#f1faee' }, label: 'Buttons', theme: 'bright' },
    { values: { color: '#432987', backgroundColor: '#ffffff', patternColor: '#c8bfd1' }, label: 'Lavender', theme: 'bright' },
    { values: { color: '#363d6b', backgroundColor: '#95c4c5', patternColor: '#c4dfec' }, label: 'Jeans', theme: 'bright' },
    { values: { color: '#364958', backgroundColor: '#c9e4ca', patternColor: '#87bba2' }, label: 'Leaf', theme: 'bright' },
    { values: { color: '#df3a55', backgroundColor: '#f3c3bd', patternColor: '#ffdece' }, label: 'Strawberry', theme: 'bright' },
    { values: { color: '#1e383e', backgroundColor: '#ffffff', patternColor: '#9bfff3' }, label: 'Diamond', theme: 'bright' },
    { values: { color: '#', backgroundColor: '', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
    { values: { color: '#', backgroundColor: '#', patternColor: '#' }, label: 'Lorem ipsum', theme: 'bright' },
]