export default [
    { label: 'Empty', value: { patternUrl: '', patternColor: '000000', patternOpacity: 1, patternScale: 1 } },
    { label: 'Stripes', value: { patternUrl: 'stripes', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Bubbles', value: { patternUrl: 'bubbles', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Triangles', value: { patternUrl: 'triangles', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Wax', value: { patternUrl: 'bee', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Piano', value: { patternUrl: 'piano', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Anchors', value: { patternUrl: 'anchors', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Checkers', value: { patternUrl: 'checkers', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Wavy', value: { patternUrl: 'wavy', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Polka', value: { patternUrl: 'polka', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Glam', value: { patternUrl: 'glam', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Wiggle', value: { patternUrl: 'wiggle', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Stars', value: { patternUrl: 'stars', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Squares', value: { patternUrl: 'squares', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Clouds', value: { patternUrl: 'clouds', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'TicTacToe', value: { patternUrl: 'tictactoe', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Minimalist', value: { patternUrl: 'autumn', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Cross', value: { patternUrl: 'hideout', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Pineapple', value: { patternUrl: 'charlie', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Donut', value: { patternUrl: 'sprinkles', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Overlap', value: { patternUrl: 'overlap', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Leaf', value: { patternUrl: 'leaf', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Shirt', value: { patternUrl: 'bathroom', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Cash', value: { patternUrl: 'bank', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Zigzag', value: { patternUrl: 'zigzag', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
    { label: 'Topographic', value: { patternUrl: 'topography', patternColor: '00ff00', patternOpacity: 1, patternScale: 1 } },
]