export default [
    { value: { patternUrl: '', patternColor: '000000', patternOpacity: 1, patternScale: 1 } },
    { value: { patternUrl: 'stripes', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { value: { patternUrl: 'bubbles', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { value: { patternUrl: 'triangles', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { value: { patternUrl: 'bee', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { value: { patternUrl: 'piano', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { value: { patternUrl: 'anchors', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { value: { patternUrl: 'checkers', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { value: { patternUrl: 'wavy', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'polka', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'glam', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'wiggle', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'stars', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'squares', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'clouds', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'tictactoe', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'autumn', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'hideout', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'charlie', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'sprinkles', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'overlap', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'leaf', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'bathroom', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'bank', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'zigzag', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
    { premium: true, value: { patternUrl: 'topography', patternColor: '00ff00', patternOpacity: 0.5, patternScale: 1 } },
]